# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: argo-api-service
spec:
  selector:
    app: argo-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
